# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: TFInstallation
    jobs:
      - job: TFInstallation
        steps:
        - task: TerraformInstaller@1
          displayName: TFInstallation
          inputs:
            terraformVersion: '1.6.6'

        - task: TerraformTask@5
          displayName: TFinit phase
          inputs:
            provider: 'azurerm'
            command: 'init'
            environmentServiceNameAzureRM: 'Azure-Service-connection'
            backendAzureRmUseEntraIdForAuthentication: true
            backendServiceArm: 'Azure-Service-connection'
            backendAzureRmResourceGroupName: 'terrafor-resource-group'
            backendAzureRmStorageAccountName: 'terraformstorage2026'
            backendAzureRmContainerName: 'terraform-tfstat'
            backendAzureRmKey: 'prod.terraform.tfstate'
  
        - task: TerraformTask@5
          displayName: plan phase
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(Build.SourcesDirectory)/terraform'
            environmentServiceNameAzureRM: 'Azure-Service-connection'

            
        
