trigger: none

pool: 
  vmImage: 'Ubuntu latest'

stages:
  - stage: deployment
    displayName: deployment
    jobs:
      - job: RGDeployment
        displayName: RGDeployment
        steps:
        - task: TerraformInstaller@1
          displayName: TerrformInstall
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          displayName: TerraformInit
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
            backendAzureRmUseEntraIdForAuthentication: false
            backendServiceArm: 'Azure-Service-connection'
            backendAzureRmResourceGroupName: 'terraform-resource-group'
            backendAzureRmStorageAccountName: 'terraformstorage2026'
            backendAzureRmContainerName: 'tfstat'
            backendAzureRmKey: 'prod.terraform.tfstate'
        
        - task: TerraformTask@5
          displayName: TerraformPlan
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
            environmentServiceNameAzureRM: 'Azure-Service-connection'

        - task: TerraformTask@5
          displayName: TerraformApply
          inputs:
            provider: 'azurerm'
            command: 'apply'
            environmentServiceNameAzureRM: 'Azure-Service-connection'