trigger: none

pool: 'ubuntu latest'

stages:
  - stage: deployment
    displayName: deployment
    jobs:
      - job: RGDeployment
        displayName: RGDeployment
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          inputs:
              provider: 'azurerm'
              command: 'init'
              backendAzureRmUseEntraIdForAuthentication: false
              backendServiceArm: 'Azure-Service-connection'
              backendAzureRmResourceGroupName: 'terraform-resource-group'
              backendAzureRmStorageAccountName: 'terraformstorage2026'
              backendAzureRmContainerName: 'tfstat'
              backendAzureRmKey: 'prod.terraform.tfstate'
        
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            environmentServiceNameAzureRM: 'Azure-Service-connection'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'
            environmentServiceNameAzureRM: 'Azure-Service-connection'